name: build-love-zip-file
run-name: Build and upload the PlaneChase.love file to latest release
on: [release]
jobs:
  build-love-zip-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest git version
        uses: actions/checkout@v3
      - name: Build core love package
        uses: love-actions/love-actions-core@v1
        with:
          build-list:   ./LICENSE ./README.md ./DejaVuSans.ttf ./images/ ./conf.lua ./main.lua
          package-path: ./PlaneChase.love
      - name: Upload core love package as artefact below (for debug)
        uses: actions/upload-artifact@v3
        with:
          name: PlaneChase.love
          path: ./PlaneChase.love
      # - name: Upload the PlaneChase.love file to latest release
      #   uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: './PlaneChase.love'
      #     repo-token: ${{ secrets.MY_SECRET_NAME }}
      #     release-tag: v0.1
      # - name: Upload the PlaneChase.love file to latest release (bis)
      #   uses: actions/upload-release-asset
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MY_SECRET_NAME }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: ./PlaneChase.love
      #     asset_name: PlaneChase.love
      #     asset_content_type: application/x-love-game
